### ISSUE TITLE
初始化编辑器失败, 请尽量使用Chrome浏览器并检查 meditorPath 配置是否正确!

### ISSUE THREAD

**Issue by Sumnus00** [BSTester/react-meditor#2]
大佬您好！
刚进来
![image](https://user-images.githubusercontent.com/17699996/133279425-d673753f-52c6-4bfa-98e5-9586798996ec.png)
然后刷新几次就这样了。
![image](https://user-images.githubusercontent.com/17699996/133278949-d73824cf-f470-4830-bb17-e885535f4d6a.png)
![image](https://user-images.githubusercontent.com/17699996/133279044-cbfd2955-1712-4a5d-91ef-1015375fd454.png)
![image](https://user-images.githubusercontent.com/17699996/133279132-3c61be13-c96e-43dd-b20e-d46d69291ed9.png)
刷新过几次页面后就会出现。不知道是哪里出了问题。
是我const minderRef = useRef(null);写的有问题么 我这个是js不是 ts..

**Comment by BSTester** [comment]
将 meditorPath  改成 /meditor/index.html 试试。
